#!/bin/bash
# Production Flags for Kumon Assistant V2
# Generated by production_flags.py

echo '🚀 Setting production flags...'

# Enforce V2 outbox handoff integrity
export OUTBOX_V2_ENFORCED=true
echo '✅ OUTBOX_V2_ENFORCED=$OUTBOX_V2_ENFORCED'

# Enforce V2 template variable stripping
export TEMPLATE_VARIABLE_POLICY_V2=true
echo '✅ TEMPLATE_VARIABLE_POLICY_V2=$TEMPLATE_VARIABLE_POLICY_V2'

# Enforce strict stage/step enum validation
export STRICT_ENUM_STAGESTEP=true
echo '✅ STRICT_ENUM_STAGESTEP=$STRICT_ENUM_STAGESTEP'

# Checkpointer backend (postgres|memory)
export CHECKPOINTER=postgres
echo '✅ CHECKPOINTER=$CHECKPOINTER'

# PostgreSQL connection URL
export DATABASE_URL=
echo '✅ DATABASE_URL=$DATABASE_URL'

# Kill-switch flags (modify as needed)
export DELIVERY_DISABLE=false  # Set to 'true' for emergency rollback
echo '⚠️  DELIVERY_DISABLE=$DELIVERY_DISABLE'

# Optional flags
export ROUTER_V2_SHADOW=false  # Set to 'true' for comparison mode
echo 'ℹ️  ROUTER_V2_SHADOW=$ROUTER_V2_SHADOW'

echo '🎯 All production flags set successfully!'