runtime: python39

# Memory optimization for production
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource limits for memory management
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  # General Configuration
  PROJECT_NAME: "Kumon AI Receptionist"
  VERSION: "1.0.0"
  DEBUG: "False"
  LOG_LEVEL: "INFO"

  # WhatsApp Business API Configuration
  WHATSAPP_VERIFY_TOKEN: "kumon_verify_token_2024"

  # OpenAI Configuration
  OPENAI_MODEL: "gpt-4o-mini"

  # Business Configuration
  BUSINESS_NAME: "Kumon"
  BUSINESS_EMAIL: "contato@kumon.com"
  BUSINESS_HOURS: "Segunda a Sexta: 8h às 18h"

  # Business Hours Configuration
  BUSINESS_HOURS_START: "9"
  BUSINESS_HOURS_END: "18"
  BUSINESS_DAYS: "[0,1,2,3,4]"
  APPOINTMENT_DURATION_MINUTES: "30"
  BUFFER_TIME_MINUTES: "15"

  # Timezone
  TIMEZONE: "America/Sao_Paulo"

  # AI Configuration
  MAX_CONVERSATION_HISTORY: "10"
  INTENT_CONFIDENCE_THRESHOLD: "0.7"
  RAG_SIMILARITY_THRESHOLD: "0.8"

  # Cache Management Settings (Production optimized)
  EMBEDDING_CACHE_SIZE_MB: "50"
  EMBEDDING_CACHE_FILES: "500"
  CACHE_CLEANUP_INTERVAL: "1800"

  # Conversation Flow Memory Management
  MAX_ACTIVE_CONVERSATIONS: "500"
  CONVERSATION_TIMEOUT_HOURS: "12"
  CONVERSATION_CLEANUP_INTERVAL: "1800"

  # Embedding Configuration (Production optimized)
  EMBEDDING_BATCH_SIZE: "16"
  EMBEDDING_DIMENSION: "384"
  EMBEDDING_MODEL_NAME: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  EMBEDDING_CACHE_DIR: "/tmp/embeddings"

  # API Configuration
  API_V1_PREFIX: "/api/v1"
  ALLOWED_HOSTS: "*"

  # Environment
  ENVIRONMENT: "production"
# Sensitive environment variables will be set via Google Cloud Console
# WHATSAPP_TOKEN, WHATSAPP_PHONE_NUMBER_ID, OPENAI_API_KEY, etc.
