steps:
  # Copy schema file to Cloud Build workspace
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "evolution_schema.sql",
        "gs://temp-schema-bucket/evolution_schema.sql",
      ]
    id: "upload-schema"

  # Apply schema to Cloud SQL
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Download schema file
        gsutil cp gs://temp-schema-bucket/evolution_schema.sql ./

        # Install PostgreSQL client
        apt-get update && apt-get install -y postgresql-client

        # Apply schema to Cloud SQL
        export PGPASSWORD="evolution123"

        # First, drop all existing tables (if any)
        psql -h /cloudsql/$PROJECT_ID:us-central1:evolution-postgres \
             -U evolution_user \
             -d evolution_db \
             -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

        # Apply the complete schema
        psql -h /cloudsql/$PROJECT_ID:us-central1:evolution-postgres \
             -U evolution_user \
             -d evolution_db \
             -f evolution_schema.sql

        echo "✅ Evolution API schema applied successfully!"

        # Verify tables were created
        psql -h /cloudsql/$PROJECT_ID:us-central1:evolution-postgres \
             -U evolution_user \
             -d evolution_db \
             -c "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public';"

        echo "🎉 Schema deployment completed!"
    id: "apply-schema"
    waitFor: ["upload-schema"]

timeout: "600s"
