steps:
  # Initialize Evolution API Database
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Install PostgreSQL client
        apt-get update && apt-get install -y postgresql-client

        # Connect to Cloud SQL and run initialization script
        export PGPASSWORD="evolution123"
        psql -h /cloudsql/$PROJECT_ID:us-central1:evolution-postgres \
             -U evolution_user \
             -d evolution_db \
             -c "
        -- Create Instance table
        CREATE TABLE IF NOT EXISTS public.\"Instance\" (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            qrcode BOOLEAN DEFAULT true,
            status TEXT DEFAULT 'disconnected',
            server_url TEXT,
            api_key TEXT,
            integration TEXT DEFAULT 'WHATSAPP-BAILEYS',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Create Message table
        CREATE TABLE IF NOT EXISTS public.\"Message\" (
            id TEXT PRIMARY KEY,
            key_remote_jid TEXT,
            key_from_me BOOLEAN DEFAULT false,
            key_id TEXT,
            pushname TEXT,
            message_type TEXT,
            message TEXT,
            instance_id TEXT REFERENCES public.\"Instance\"(id) ON DELETE CASCADE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Grant permissions
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO evolution_user;

        -- Test record
        INSERT INTO public.\"Instance\" (id, name, qrcode, status, integration) 
        VALUES ('test-init', 'initialization-test', true, 'disconnected', 'WHATSAPP-BAILEYS') 
        ON CONFLICT (name) DO NOTHING;

        SELECT 'Evolution API database initialized successfully!' as result;
        "

        echo "Database initialization completed!"
    id: "init-evolution-db"

timeout: "600s"
