runtime: python39

env_variables:
  # General Configuration
  PROJECT_NAME: "Kumon AI Receptionist"
  VERSION: "1.0.0"
  DEBUG: "False"
  LOG_LEVEL: "INFO"

  # WhatsApp Business API Configuration
  WHATSAPP_VERIFY_TOKEN: "kumon_verify_token_2024"

  # OpenAI Configuration
  OPENAI_MODEL: "gpt-4-turbo-preview"

  # Business Configuration
  BUSINESS_NAME: "Kumon"
  BUSINESS_EMAIL: "contato@kumon.com"
  BUSINESS_HOURS: "Segunda a Sexta: 8h às 18h"

  # Business Hours Configuration
  BUSINESS_HOURS_START: "8"
  BUSINESS_HOURS_END: "18"
  BUSINESS_DAYS: "[0,1,2,3,4]"
  APPOINTMENT_DURATION_MINUTES: "60"
  BUFFER_TIME_MINUTES: "15"

  # Timezone
  TIMEZONE: "America/Sao_Paulo"

  # AI Configuration
  MAX_CONVERSATION_HISTORY: "10"
  INTENT_CONFIDENCE_THRESHOLD: "0.7"
  RAG_SIMILARITY_THRESHOLD: "0.8"

  # API Configuration
  API_V1_PREFIX: "/api/v1"
  ALLOWED_HOSTS: "*"
# Sensitive environment variables will be set via Google Cloud Console
# WHATSAPP_TOKEN, WHATSAPP_PHONE_NUMBER_ID, OPENAI_API_KEY, etc.
