services:
  # Evolution API v1 - Simple Configuration
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.7.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=B6D711FCDE4D4FD5936544120E713976
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  # Keep other services for your Kumon Assistant
  qdrant:
    container_name: qdrant_db
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - evolution-net

  # Kumon Assistant Application
  kumon-assistant:
    container_name: kumon_assistant
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./app/data:/app/app/data
    depends_on:
      - evolution-api
      - qdrant
    networks:
      - evolution-net
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EVOLUTION_API_URL=http://evolution-api:8080

volumes:
  evolution_instances:
  qdrant_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
