version: "3"
services:
  # Evolution API for WhatsApp integration
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
    networks:
      - kumon_network

  # Qdrant Vector Database for embeddings
  qdrant:
    container_name: qdrant_db
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334" # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - kumon_network

  # Kumon Assistant Application (optional - for containerized deployment)
  kumon-assistant:
    container_name: kumon_assistant
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./app/data:/app/app/data
    depends_on:
      - evolution-api
      - qdrant
    networks:
      - kumon_network
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EVOLUTION_API_URL=http://evolution-api:8080

volumes:
  evolution_store:
  evolution_instances:
  qdrant_data:

networks:
  kumon_network:
    driver: bridge
